
name: '[CI/CD] CD Pipeline'
on: # main branch changes
  push:
    branches:
      - main
permissions: {}
# Avoid concurrency over the same commit
concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
jobs:
  get-containers:
    runs-on: ubuntu-latest
    name: Get modified containers
    permissions:
      contents: read
    outputs:
      result: ${{ steps.get-containers.outputs.result }}
      containers: ${{ steps.get-containers.outputs.containers }}
      dockerfiles: ${{ steps.get-containers.outputs.dockerfiles }}
    steps:
      - id: get-containers
        name: Get modified containers
        env:
          COMMIT_REF: "${{ github.sha }}"
          GITHUB_TOKEN: "${{ github.token }}"
        run: |
          files_changed="$(gh api --paginate /repos/${GITHUB_REPOSITORY}/commits/${COMMIT_REF} | jq -r '.files.[] | .filename')"
          # Adding || true to avoid "Process exited with code 1" errors
          flavors=($(echo "$files_changed" | xargs dirname | grep -o "^bitnami/[^/]*/[^/]*/[^/]*" | sort | uniq || true))
          assets=($(echo "$files_changed" | xargs dirname | sed -nr "s|bitnami/([^/]*)/.*|\1|p" | sort | uniq || true))
          non_readme_files=$(echo "$files_changed" | grep -vc "\.md" || true)
          dockerfiles=($(echo "$files_changed" | grep -oE ".*/Dockerfile$" | sort | uniq || true))

          if [[ "$non_readme_files" -le "0" ]]; then
            # The only changes are .md files -> SKIP
            echo "result=skip" >> $GITHUB_OUTPUT
          elif [[ "${#assets[@]}" -ge "5" ]]; then
            echo "Maximun number of assets reached. You are currently modifying: ${assets[@]}"
            echo "result=skip" >> $GITHUB_OUTPUT
          else
            containers_json=$(printf "%s\n" "${flavors[@]}" | jq -R . | jq -cs .)
            dockerfiles_json=$(printf "%s\n" "${dockerfiles[@]}" | jq -R . | jq -cs .)
            echo "result=ok" >> $GITHUB_OUTPUT
            echo "containers=${containers_json}" >> $GITHUB_OUTPUT
            echo "dockerfiles=${dockerfiles_json}" >> $GITHUB_OUTPUT
          fi
  build-images:
    runs-on: ubuntu-latest
    name: Build images
    needs:
      - get-containers
    if: ${{ needs.get-containers.outputs.result == 'ok' && needs.get-containers.outputs.containers != '[""]' && needs.get-containers.outputs.containers != '[]' && needs.get-containers.outputs.containers != '' }}
    strategy:
      matrix:
        container: ${{ fromJSON(needs.get-containers.outputs.containers) }}
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Check out repository code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Prepare image name
        run: |
          APP_PATH="${{ matrix.container}}"
          cd ${APP_PATH}
          APP_NAME=$(echo "${APP_PATH}" | awk -F/ '{print $2}')
          APP_VERSION=$(cat Dockerfile | grep APP_VERSION= | grep -o '".*"' | tr -d '"')
          IMAGE_REVISION=$(cat Dockerfile | grep IMAGE_REVISION= | grep -o '[0-9]*' || echo 0)
          OS_FLAVOUR=$(echo "${APP_PATH}" | awk -F/ '{print $4}')
          echo "FULL_IMAGE_NAME=${REGISTRY}/${GITHUB_REPOSITORY}/${APP_NAME}:${APP_VERSION}-${OS_FLAVOUR}-r${IMAGE_REVISION}" >> $GITHUB_ENV

      - name: Build docker image
        uses: m-wrzesien/gh-actions/.github/actions/docker-build@master
        with:
          context: ${{ matrix.container }}
          tag: ${{ env.FULL_IMAGE_NAME }}

      - name: Log in to the Container registry
        uses: m-wrzesien/gh-actions/.github/actions/docker-login@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Push docker image
        uses: m-wrzesien/gh-actions/.github/actions/docker-push@master
        with:
          tag: ${{ env.FULL_IMAGE_NAME }}
